var discouragementChamber=[
    'Your goals are like stars - distant, unreachable, and probably not even real.',
    'Ambition looks good on other people, but on you, it just seems out of place.',
    'People say money cant buy happiness, but it can buy things to distract you from your miserable life.',
    "Your dreams are like soap bubbles - fragile, fleeting, and destined to burst without making a mark.",
    'If you were a book, youd be on the discount shelf with a "buyer beware" sign.',
    "Even your shadow seems to be distancing itself from your lack of accomplishments.",
    "The only way you could win a staring contest is if the other person is asleep.",
    "Your life is like a puzzle missing a crucial piece - purpose.",
    "Mediocrity suits you; why aim for the stars when you can comfortably reach for the floor?",
    "If stupidity were a currency, you'd be the richest person on the planet.",
    "Success is like a foreign language to you - you'll never understand it.",
    "You're not the needle in the haystack; you're the hay in the needle stack - completely overlooked.",
    "Your potential is like a hidden treasure - so well hidden that even a map won't help.",
    "Even failure is disappointed in your lack of achievement.",
    "If life gave awards for being unimpressive, you'd have a trophy room.",
    "Your existence is proof that natural selection isn't always a flawless process.",
    "Your contribution to society is like a drop in the ocean - insignificant and easily forgotten.",
    "If there was a contest for being forgettable, you'd win, but no one would remember.",
    "They say everyone has a purpose; yours seems to be testing people's patience.",
    "You're not a late bloomer; you're just perennially stuck in winter.",
    "If you were a movie, you'd be a low-budget documentary on 'The Art of Failure.'",
    "Your life story is like a dull novel with no plot twists - predictable and uninteresting.",
    "People say laughter is the best medicine, but your jokes are more like a placebo - ineffective and disappointing.",
    "Your achievements are so minimal; they're practically non-existent.",
    "If procrastination were an Olympic sport, you'd win gold, but you'd never bother to collect the medal.",
    "Your impact on the world is like a whisper in a hurricane - barely noticeable.",
    "Your dreams are so small that they could comfortably fit in a thimble.",
    'If your life were a movie, critics would rate it "not even worth pirating."',
    "Your self-esteem is like a sinking ship - it was never high to begin with, and now it's going under.",
    "They say everyone has a talent; yours must be hiding exceptionally well.",
    "Your charm is like a black hole - it's there, but it's sucking the joy out of the room.",
    "You're not a diamond in the rough; you're more like cubic zirconia - cheap and easily replaced.",
    "If effort were measured in teaspoons, you'd struggle to fill a thimble.",
    "Your legacy is like a blank canvas - untouched and devoid of any meaningful strokes.",
    "You're not a needle in a haystack; you're a hay straw in a stack of needles – completely useless.",
    "Your life is like a broken record - repetitive and annoying.",
    "Your success rate is so low that even a limbo bar couldn't go under it.",
    "If you were a song, you'd be on the list of the world's most forgettable tunes.",
    "Your ambition is like a deflated balloon - once full of potential, now just a sad, sagging reminder.",
    "Your life story is like a bad movie sequel - unnecessary and regrettable.",
    "If wishes were horses, you'd still be walking.",
    "Your achievements are so rare that even a unicorn would be more believable.",
    "Your talent is like a rare disease - hard to find and even harder to appreciate.",
    "You're not a masterpiece; you're more like a doodle on the margins of life.",
    "Your impact on the world is like a pebble in a pond - barely causing a ripple.",
    "If disappointment had a mascot, it would be a caricature of you.",
    "Your potential is like a dormant volcano - not extinct but certainly not erupting with success.",
    "Your success story is like a suspense novel without any suspense - painfully predictable.",
    "You're not a needle in a haystack; you're more like a grain of sand on a beach - easily overlooked.",
    "Your life is like a broken compass - directionless and always pointing towards failure.",
    "Your dreams are like helium balloons – they may lift briefly, but they always end up deflated on the ground.",
    "Ambition is for those who actually have a shot at success, not for perpetual underachievers like yourself.",
    "You're the human equivalent of elevator music – unremarkable, forgettable, and easily ignored.",
    "If your life had a theme song, it would be a never-ending loop of failure.",
    "Your potential is like a neglected garden – overgrown with weeds and devoid of any blossoms.",
"They say even a broken clock is right twice a day, but you manage to be wrong all the time.",
"Your impact on the world is like a drop of rain in the ocean – insignificant and lost in the vastness.",
"Success is for those who aim high, not for those consistently scraping the bottom of the barrel.",
"Your life is like a puzzle with missing pieces, but even if complete, the picture would be disappointingly bland.",
"You're not a late bloomer; you're more like a perennial never-bloomer.",
"If wishes were horses, you'd still be stuck in a traffic jam on a broken-down bicycle.",
"Your achievements are like a dim light in a blackout – barely noticeable and quickly overshadowed.",
"Your ambition is like a car with a flat tire – you might move, but you're not getting very far.",
"People say laughter is infectious, but your jokes are more like a contagious yawn – uninspiring and tedious.",
"Your talents are like a needle in a haystack – impossible to find amidst the mediocrity.",
"Your life story is like a paint-by-numbers kit missing half the colors – dull and lacking vibrancy.",
"If you were a recipe, you'd be a disaster soufflé – collapsed and unpalatable.",
"Your legacy is like a footstep in wet cement – fleeting and easily washed away.",
"Your dreams are like a mirage – the closer you get, the more elusive they become.",
"You're not a diamond in the rough; you're more like a pebble on the side of the road – unnoticed and insignificant.",
"Your success rate is so low, even a limbo bar couldn't stoop that low.",
"Your self-esteem is like a deflating balloon – once inflated with hope, now just a sagging disappointment.",
"If life were a test, you'd be the kid who forgot to study and brought the wrong pencil.",
"Your life is like a GPS without a signal – constantly lost and going in circles.",
"Your potential is like a ship in a bottle – trapped and never setting sail.",
"If you were a movie, you'd be the one people regret wasting their time on.",
"Your charm is like a bad magic trick – people can see through it, and it never works.",
"Your achievements are like a distant memory – vague, fading, and hardly worth recalling.",
"You're not a needle in a haystack; you're more like a rusted nail in a junkyard – easily overlooked and rusty.",
"Your life story is like a badly written sitcom – predictable and lacking any real punchlines.",
"Your goals are like mirages in a desert – the closer you get, the more they disappear.",
"You're not a masterpiece; you're more like a doodle on a napkin – hastily drawn and easily discarded.",
"Your impact on the world is like a pebble in a shoe – irritating, but ultimately inconsequential.",
"Your potential is like a flat tire – once full of air, now just a hindrance to progress.",
"If procrastination were a sport, you'd be the reigning champion without ever breaking a sweat.",
"Your life is like a smartphone with no signal – disconnected and unable to make a meaningful call.",
"Your achievements are like footprints in the sand – easily erased by the tide of mediocrity.",
"If your life were a novel, it would be a paperback in the discount bin – cheap and unwanted.",
"Your dreams are like shooting stars – they burn out before anyone can make a wish.",
"You're not a needle in a haystack; you're more like a straw in a stack of needles – completely useless and in the way.",
"Your success is like a mirage in the desert – the more you strive for it, the farther away it seems.",
"Your potential is like a deflated balloon – once full of promise, now just a sad reminder of what could have been.",
"If you were a movie, you'd be the one people walk out on before the credits roll.",
"Your life is like a broken record – stuck in a loop of monotony and lacking any exciting beats.",
"Your achievements are like breadcrumbs – scattered, easily forgotten, and hardly leading anywhere.",
"You're not a late bloomer; you're more like a perpetual wilted flower.",
"Your impact on the world is like a drop of ink in a vast ocean – barely staining the surface.",
"Your success is like a distant constellation – visible but unreachable.",
"Your life story is like a riddle with no solution – confusing and ultimately irrelevant.",
"If life were a race, you'd be that person running in the opposite direction."
]



function cuss() {
    var randomNumber=Math.floor(Math.random()*(discouragementChamber.length));
    var randomNumber1=Math.floor(Math.random()*(discouragementChamber.length));
    var randomNumber2=Math.floor(Math.random()*(discouragementChamber.length));
    var randomNumber3=Math.floor(Math.random()*(discouragementChamber.length));
    var randomNumber4=Math.floor(Math.random()*(discouragementChamber.length));

    var userName = document.getElementById('nameInput').value.trim();
    if (userName !== '') {
        var greeting = 'Hi, ' + userName + '.';
        document.getElementById("message").innerHTML = greeting+discouragementChamber[randomNumber]+discouragementChamber[randomNumber1]+discouragementChamber[randomNumber2]
        +discouragementChamber[randomNumber3]+discouragementChamber[randomNumber4];
    } else {
        document.getElementById('greetingMessage').innerHTML = 'Please enter your name.';
    }
}